### ISSUE TITLE
jest only changed files support

### ISSUE THREAD

**Issue by awitherow** [DanielMSchmidt/dev-bro#1]
looking at the jest running implementation, it is much slower if the project has a number of tests... because it takes time to execute the entire suite.

it would be great to be able to pass something like `jest--watch` or so to `dev-bro` and be able to manipulate how jest will work.

**Comment by DanielMSchmidt** [comment]
It shouldn't execute the complete suite. Jest is called with the `-o` flag, it "attempts to identify which tests to run based repository. Only works if you're running tests in a git repository at the moment". This should be what `--watch` should use under the hood

**Comment by awitherow** [comment]
Ah alright, I made false assumptions then based on the speed.

**Comment by DanielMSchmidt** [comment]
Okay, no worries 👍
